"""FastAPIプロジェクト共通ツールキット。"""

from fastapi_toolkit.logging import get_logger, setup_logging
from fastapi_toolkit.middleware import (
    AccessLogMiddleware,
    CacheControlMiddleware,
    COEPMiddleware,
    COOPMiddleware,
    CORPMiddleware,
    CSPMiddleware,
    DNSPrefetchControlMiddleware,
    FrameGuardMiddleware,
    HostValidationMiddleware,
    HSTSMiddleware,
    JsonContentTypeMiddleware,
    NoSniffMiddleware,
    OriginValidationMiddleware,
    PermissionsPolicyMiddleware,
    ReferrerPolicyMiddleware,
    RobotsTagMiddleware,
    ServerHeaderStripMiddleware,
    SSEBufferingMiddleware,
    XSSProtectionMiddleware,
)

__all__ = [
    "AccessLogMiddleware",
    "CacheControlMiddleware",
    "COEPMiddleware",
    "COOPMiddleware",
    "CORPMiddleware",
    "CSPMiddleware",
    "DNSPrefetchControlMiddleware",
    "FrameGuardMiddleware",
    "HostValidationMiddleware",
    "HSTSMiddleware",
    "JsonContentTypeMiddleware",
    "NoSniffMiddleware",
    "OriginValidationMiddleware",
    "PermissionsPolicyMiddleware",
    "ReferrerPolicyMiddleware",
    "RobotsTagMiddleware",
    "ServerHeaderStripMiddleware",
    "SSEBufferingMiddleware",
    "XSSProtectionMiddleware",
    "get_logger",
    "setup_logging",
]
